[package]
name = "bulletin-bot"
version = "0.1.0"
authors = ["Serge Barinov <bool.rus@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tbot = "0.6"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "sync"]}
teloxide = { version = "0.8", features = ["macros", "auto-send"] }

log = "0.4"
simplelog = "0.12"

num-format = "0.4.0"

serde = { version = "1.0", features = ["derive"] }
strum = "0.24"
strum_macros = "0.24"
ron = "0.7"
