[package]
name = "bulletin-bot"
version = "0.1.0"
authors = ["Serge Barinov <bool.rus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tbot='*'
tokio = { version = "0.2", features = ["macros"] }
