[package]
name = "bulletin-bot"
version = "0.1.0"
authors = ["Serge Barinov <bool.rus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tbot = "0.6"
tokio = { version = "0.2", features = ["macros"] }

log = "0.4"
simplelog = "0.10"

num-format = "0.4.0"
